### ISSUE TITLE
 can I read your articles?

### ISSUE THREAD

**Issue by Pinocchio96** [uf-hobi-informatics-lab/seqEHR#21]
Hi, I think your work is great, and I would like to know if your work has been published, can I read your articles? If unpublished, how can I cite if I want to use your method? thanks

**Comment by bugface** [comment]
Thank you for your interest in our project.  Unfortunately, we do not have a paper on this.  If you need to use the code, please feel free and if you can acknowledge us in your acknowledgment section, that will be great.  

The repo is still under development, if you can contribute, it will be excellent.

**Comment by Pinocchio96** [comment]
Thanks for your reply.
